'use strict';
const $=id=>document.getElementById(id),M=MusicModel;
let context,masterNode,analyser,tracks=[],position=0,playing=false,startedAt=0,sources=[],undo=[],redo=[],recorder=null,stream=null,recordStart=0,dirty=false,busy=false;
const buffers=new Map();
function status(msg,error=false){$('status').textContent=msg;$('status').classList.toggle('error',error);}
async function audio(){if(!context){context=new AudioContext();masterNode=context.createGain();masterNode.gain.value=Number($('master').value);analyser=context.createAnalyser();analyser.fftSize=2048;masterNode.connect(analyser);analyser.connect(context.destination);}await context.resume();return context;}
function total(){return Math.max(1,...tracks.map(t=>t.start+t.trimEnd-t.trimStart));}
function timeline(){return Math.max(16,total()+2);}
function current(){return playing?Math.max(position,position+context.currentTime-startedAt):position;}
function snapshot(){return JSON.stringify({tracks,name:$('name').value,bpm:$('bpm').value,master:$('master').value});}
function mark(){undo.push(snapshot());if(undo.length>40)undo.shift();redo=[];dirty=true;}
function restore(value){pause();const d=JSON.parse(value);tracks=d.tracks;$('name').value=d.name;$('bpm').value=d.bpm;$('master').value=d.master;if(masterNode)masterNode.gain.value=Number(d.master);position=Math.min(position,total());dirty=true;render();}
function halt(){for(const s of sources){try{s.stop();}catch{}}sources=[];}
function pause(){if(playing){position=current();playing=false;halt();}renderButtons();}
function stop(){pause();position=0;frame();}
function schedule(ctx,out,t,pos,base){
 const p=M.plan(t,pos);if(!p)return;const source=ctx.createBufferSource(),gain=ctx.createGain(),pan=ctx.createStereoPanner();source.buffer=buffers.get(t.id);pan.pan.value=t.pan;
 const at=base+p.delay,points=M.envelope(t,p);gain.gain.setValueAtTime(points[0].value,at);for(const point of points.slice(1))gain.gain.linearRampToValueAtTime(point.value,at+point.time);
 source.connect(gain);gain.connect(pan);pan.connect(out);source.start(at,p.offset,p.duration);return source;
}
async function play(){if(playing||busy||recorder)return;if(!tracks.length)return status('Voeg eerst audio toe.');const ctx=await audio();if(position>=total())position=0;startedAt=ctx.currentTime+0.03;playing=true;sources=M.audible(tracks).map(t=>schedule(ctx,masterNode,t,position,startedAt)).filter(Boolean);renderButtons();status('Mix wordt afgespeeld.');}
function renderButtons(){for(const id of ['import','demo','open','save','export','new'])$(id).disabled=busy||!!recorder;document.querySelectorAll('.controls input,.track-head button,.track-head input').forEach(i=>i.disabled=busy||!!recorder);$('play').disabled=playing||busy||!!recorder;$('record').textContent=recorder?'■ Opname stoppen':'● Microfoon opnemen';$('record').classList.toggle('recording',!!recorder);$('undo').disabled=!undo.length||busy||!!recorder;$('redo').disabled=!redo.length||busy||!!recorder;}
function seek(value){const resume=playing;pause();position=Math.max(0,Math.min(total(),value));frame();if(resume)play().catch(e=>status(e.message,true));}
function edit(t,key,value){const resume=playing;pause();mark();const b=buffers.get(t.id);Object.assign(t,M.cleanClip({...t,[key]:value},b.duration));render();if(resume)play().catch(e=>status(e.message,true));}
function control(row,t,label,key,type,min,max,step){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type=type;i.min=min;i.max=max;i.step=step;i.value=t[key];i.setAttribute('aria-label',label+' '+t.name);i.onchange=()=>edit(t,key,Number(i.value));l.append(i);row.append(l);}
function render(){
 $('tracks').replaceChildren();$('ruler').replaceChildren();$('empty').hidden=tracks.length>0;const span=timeline(),beat=60/Math.max(30,Math.min(300,Number($('bpm').value)||120)),spacing=Math.max(beat*4,span/14);
 for(let at=0;at<span;at+=spacing){const tick=document.createElement('span');tick.className='tick';tick.style.left=(at/span*100)+'%';tick.textContent=at.toFixed(1)+'s';$('ruler').append(tick);}
 for(const t of tracks){const article=document.createElement('section');article.className='track';const head=document.createElement('div');head.className='track-head';const name=document.createElement('input');name.className='name';name.value=t.name;name.setAttribute('aria-label','Spoornaam');name.onchange=()=>edit(t,'name',name.value);head.append(name);
  for(const [label,key] of [['M','mute'],['S','solo']]){const b=document.createElement('button');b.textContent=label;b.title=key==='mute'?'Dempen':'Solo';b.setAttribute('aria-pressed',String(t[key]));b.classList.toggle('active',t[key]);b.onclick=()=>edit(t,key,!t[key]);head.append(b);}
  const duplicate=document.createElement('button');duplicate.textContent='＋ Kopie';duplicate.onclick=()=>{pause();mark();const copy={...t,id:crypto.randomUUID(),name:t.name+' kopie',start:t.start+t.trimEnd-t.trimStart};buffers.set(copy.id,buffers.get(t.id));tracks.push(copy);render();};head.append(duplicate);
  const remove=document.createElement('button');remove.textContent='×';remove.title='Spoor verwijderen';remove.className='danger';remove.onclick=()=>{pause();mark();tracks=tracks.filter(x=>x.id!==t.id);render();};head.append(remove);article.append(head);
  const wave=document.createElement('div');wave.className='wave';const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=84;wave.append(canvas);const line=document.createElement('div');line.className='playhead';wave.append(line);wave.onclick=e=>seek((e.clientX-wave.getBoundingClientRect().left)/wave.clientWidth*span);article.append(wave);
  const controls=document.createElement('div');controls.className='controls';control(controls,t,'Start (s)','start','number',0,86400,.1);control(controls,t,'Begin bron (s)','trimStart','number',0,buffers.get(t.id).duration,.1);control(controls,t,'Einde bron (s)','trimEnd','number',0,buffers.get(t.id).duration,.1);control(controls,t,'Volume','gain','range',0,2,.01);control(controls,t,'Pan L/R','pan','range',-1,1,.01);control(controls,t,'Fade in (s)','fadeIn','number',0,86400,.1);control(controls,t,'Fade uit (s)','fadeOut','number',0,86400,.1);article.append(controls);$('tracks').append(article);drawWave(canvas,t,span);
 }
 renderButtons();frame();
}
function drawWave(canvas,t,span){const ctx=canvas.getContext('2d'),data=buffers.get(t.id).getChannelData(0),rate=buffers.get(t.id).sampleRate,w=canvas.width,h=canvas.height,begin=t.start/span*w,end=(t.start+t.trimEnd-t.trimStart)/span*w;ctx.fillStyle=t.mute?'#203542':'#0e425b';ctx.fillRect(begin,0,end-begin,h);ctx.strokeStyle=t.solo?'#ffca73':'#37bbec';ctx.beginPath();const pixels=Math.max(1,Math.ceil(end-begin));for(let p=0;p<pixels;p++){const a=Math.floor((t.trimStart+p/pixels*(t.trimEnd-t.trimStart))*rate),b=Math.min(data.length,Math.ceil((t.trimStart+(p+1)/pixels*(t.trimEnd-t.trimStart))*rate));let peak=0;for(let i=a;i<b;i+=Math.max(1,Math.floor((b-a)/64)))peak=Math.max(peak,Math.abs(data[i]));const x=begin+p;ctx.moveTo(x,h/2-peak*h*.44);ctx.lineTo(x,h/2+peak*h*.44);}ctx.stroke();}
function frame(){const p=Math.max(0,current());$('clock').textContent=String(Math.floor(p/60)).padStart(2,'0')+':'+(p%60).toFixed(2).padStart(5,'0');document.querySelectorAll('.playhead').forEach(l=>l.style.left=(p/timeline()*100)+'%');if(playing&&p>=total()){pause();position=total();status('Einde van de mix.');}if(analyser){const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);let peak=0;for(const x of data)peak=Math.max(peak,Math.abs(x));$('meter').value=Math.min(1,peak);$('level').textContent=peak>0.00001?(20*Math.log10(peak)).toFixed(1)+' dB':'−∞ dB';}}
setInterval(frame,40);
async function addFile(file,start=0){const ctx=await audio(),raw=await file.arrayBuffer();let buffer;try{buffer=await ctx.decodeAudioData(raw);}catch{throw new Error(file.name+': dit audioformaat kan hier niet worden gedecodeerd.');}const id=crypto.randomUUID();buffers.set(id,buffer);tracks.push(M.cleanClip({id,name:file.name.replace(/\.[^.]+$/,''),start,trimEnd:buffer.duration,gain:1,pan:0,fadeIn:0,fadeOut:0},buffer.duration));}
async function importFiles(files){if(busy)return;busy=true;pause();mark();renderButtons();let count=0,errors=[];for(const f of files){try{await addFile(f);count++;status('Geladen: '+f.name);}catch(e){errors.push(e.message);}}busy=false;render();status(count+' spoor/sporen toegevoegd.'+(errors.length?' '+errors.join(' '):''),errors.length>0);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(){return $('name').value.replace(/[^\p{L}\p{N} _-]/gu,'').trim()||'The One mix';}
function base64(bytes){let str='';for(let at=0;at<bytes.length;at+=16384)str+=String.fromCharCode(...bytes.subarray(at,at+16384));return btoa(str);}
async function save(){if(busy)return;busy=true;renderButtons();status('Project inclusief audio opslaan…');try{const media={};for(const t of tracks)media[t.id]=base64(new Uint8Array(M.wav(buffers.get(t.id))));const project={format:'the-one-music-maker',version:1,name:$('name').value,bpm:Number($('bpm').value),master:Number($('master').value),tracks,media};download(new Blob([JSON.stringify(project)],{type:'application/json'}),filename()+'.onemusic');dirty=false;status('Project opgeslagen inclusief audio.');}catch(e){status('Opslaan mislukt: '+e.message,true);}finally{busy=false;renderButtons();}}
async function openProject(file){if(!file||busy)return;busy=true;pause();renderButtons();try{const d=JSON.parse(await file.text());if(d.format!=='the-one-music-maker'||d.version!==1||!Array.isArray(d.tracks)||d.tracks.length>200)throw new Error('Geen ondersteund Music Maker-project.');const ctx=await audio(),next=[],decoded=new Map();const ids=new Set();for(const t of d.tracks){if(typeof t.id!=='string'||ids.has(t.id)||typeof d.media?.[t.id]!=='string')throw new Error('Project bevat ongeldige audio.');ids.add(t.id);const bin=atob(d.media[t.id]),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));const b=await ctx.decodeAudioData(bytes.buffer);decoded.set(t.id,b);next.push(M.cleanClip({...t,name:String(t.name||'Audio')},b.duration));}mark();decoded.forEach((v,k)=>buffers.set(k,v));tracks=next;$('name').value=String(d.name||'Mijn mix');$('bpm').value=Math.min(300,Math.max(30,Number(d.bpm)||120));$('master').value=Math.min(1,Math.max(0,Number(d.master)||0));masterNode.gain.value=Number($('master').value);position=0;dirty=false;status('Project geladen inclusief audio.');}catch(e){status('Openen mislukt: '+e.message,true);}finally{busy=false;render();}}
async function exportMix(){if(busy||!tracks.length)return;busy=true;renderButtons();status('Mix naar stereo WAV renderen…');try{const seconds=total();if(seconds>1800)throw new Error('Deze preview exporteert maximaal 30 minuten per mix.');const ctx=new OfflineAudioContext(2,Math.ceil(seconds*44100),44100),out=ctx.createGain();out.gain.value=Number($('master').value);out.connect(ctx.destination);for(const t of M.audible(tracks))schedule(ctx,out,t,0,0);const rendered=await ctx.startRendering();let peak=0;for(let c=0;c<2;c++)for(const x of rendered.getChannelData(c))peak=Math.max(peak,Math.abs(x));if(peak>1){for(let c=0;c<2;c++){const data=rendered.getChannelData(c);for(let i=0;i<data.length;i++)data[i]/=peak;}}download(new Blob([M.wav(rendered)],{type:'audio/wav'}),filename()+'.wav');status('Stereo WAV geëxporteerd.'+(peak>1?' De pieken zijn verlaagd om vervorming te voorkomen.':''));}catch(e){status('Export mislukt: '+e.message,true);}finally{busy=false;renderButtons();}}
async function recording(){if(recorder){recorder.stop();return;}if(busy)return;try{pause();await audio();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});recordStart=position;const chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{const type=recorder.mimeType;stream.getTracks().forEach(t=>t.stop());stream=null;recorder=null;mark();try{await addFile(new File(chunks,'Microfoon '+new Date().toLocaleTimeString('nl-NL')+'.webm',{type}),recordStart);status('Microfoonopname toegevoegd.');}catch(e){status(e.message,true);}render();};recorder.onerror=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;recorder=null;status('Microfoonopname mislukt.',true);renderButtons();};recorder.start();status('Microfoon neemt op. Klik op Opname stoppen.');renderButtons();}catch(e){stream?.getTracks().forEach(t=>t.stop());stream=null;status('Microfoon niet beschikbaar: '+e.message,true);}}
async function demo(){if(busy)return;pause();mark();const ctx=await audio();for(let track=0;track<2;track++){const id=crypto.randomUUID(),b=ctx.createBuffer(1,ctx.sampleRate*8,ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++){const sec=i/ctx.sampleRate,phase=sec%.5,envelope=Math.exp(-phase*(track===0?24:8));data[i]=Math.sin(2*Math.PI*(track===0?65:220)*sec)*envelope*.25;}buffers.set(id,b);tracks.push(M.cleanClip({id,name:track===0?'Demo · Kick':'Demo · Synth',start:track*.25,trimEnd:8,gain:1,pan:track===0?-.2:.2,fadeIn:.03,fadeOut:.5},8));}render();status('Twee demosporen geladen.');}
$('import').onclick=()=>$('files').click();$('files').onchange=e=>{importFiles(e.target.files);e.target.value='';};$('open').onclick=()=>$('project').click();$('project').onchange=e=>{const f=e.target.files[0];openProject(f);e.target.value='';};$('play').onclick=()=>play().catch(e=>status(e.message,true));$('pause').onclick=pause;$('stop').onclick=stop;$('record').onclick=recording;$('demo').onclick=()=>demo().catch(e=>status(e.message,true));$('save').onclick=save;$('export').onclick=exportMix;
$('undo').onclick=()=>{if(undo.length){redo.push(snapshot());restore(undo.pop());}};$('redo').onclick=()=>{if(redo.length){undo.push(snapshot());restore(redo.pop());}};
$('new').onclick=()=>{if(recorder)return status('Stop eerst de opname.');if(dirty&&!confirm('Nieuw project starten? Sla je huidige project eerst op om het te bewaren.'))return;pause();mark();tracks=[];position=0;$('name').value='Mijn eerste mix';render();};
$('master').oninput=()=>{dirty=true;if(masterNode)masterNode.gain.setTargetAtTime(Number($('master').value),context.currentTime,.01);};$('bpm').onchange=()=>{dirty=true;$('bpm').value=Math.min(300,Math.max(30,Number($('bpm').value)||120));render();};$('name').onchange=()=>dirty=true;
$('ruler').onclick=e=>seek((e.clientX-$('ruler').getBoundingClientRect().left)/$('ruler').clientWidth*timeline());
window.addEventListener('beforeunload',e=>{if(dirty||recorder){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||e.code!=='Space')return;e.preventDefault();if(playing)pause();else play().catch(e=>status(e.message,true));});
render();
