plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gmailorg.thedj'
    compileSdk 34

    defaultConfig {
        applicationId 'com.gmailorg.thedj'
        minSdk 26
        targetSdk 34
        versionCode (project.findProperty('appVersionCode') ?: '1').toInteger()
        versionName "1." + versionCode
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
